config/routes.rb
Racedayphotos::Application.routes.draw do
  resources :events

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }, 
        path_names: { sign_in: "login", sign_out: "logout", sign_up: "register" }

  resources :users
    
  resources :locations

  get "main/index"

  root 'main#index'

  resources :photos
    

end

app/models/photo.rb
class Photo < ActiveRecord::Base

  belongs_to :user
  belongs_to :location
  belongs_to :event

  has_attached_file :image, :styles => { :large => "700x700", :medium => "300x300>", :thumb => "100x100>" }, 
    :default_url => "/images/:style/missing.png",
    :url  => "/assets/photos/:id/:style/:basename.:extension",
    :path => ":rails_root/public/assets/photos/:id/:style/:basename.:extension"
      
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/  

  after_image_post_process :load_location_info
  
  # Allow all Photos from a photographer be moved to a new photographer
  def self.move_to_new_photographer(old_photographer, new_photographer) 
    photos_to_be_moved = Photo.where(user_id: old_photographer.id)
    photos_to_be_moved.each { |photo| 
      photo.user = new_photographer
      photo.save!
    }
  end

  # Allow this photo to be moved to a new photographer
  def move_to_new_photographer(new_photographer)
    self.user = new_photographer
    self.save!
  end
  
  # After the photo has been uploaded, process the exif info it has.
  def load_location_info
    
    begin
      exif = EXIFR::JPEG.new(self.image.queued_for_write[:original].path)
  
      if not exif.nil? && exif.exif?
        
        if exif.date_time.present?
          self.date_taken = exif.date_time.to_date 
        else
          Rails.logger.debug "\n\n LOAD_LOCATION_INFO exif #{exif.inspect} \n\n"
          Rails.logger.debug "\n\n image #{self.image.inspect} \n\n"
          #self.date_taken = self.date_created
        end
        
        if not exif.gps.nil?
          longitude = exif.gps.longitude
          latitude = exif.gps.latitude
          altitude = exif.gps.altitude
          image_direction = exif.gps.image_direction
          description =  !longitude.nil? && !latitude.nil? ? "Map location available" : ""

          location = Location.create(description: description, longitude: exif.gps.longitude, latitude: exif.gps.latitude, altitude: exif.gps.altitude, image_direction:exif.gps.image_direction)
        else
          location = Location.create()
        end
      end
    rescue EXIFR::MalformedJPEG
      Rails.logger.error "Malformed JPG. Could not get EXIF data."
      location = Location.create()
    end
    self.location = location
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  before_action :save_return_to, only: [:show, :edit, :update]
  after_action :save_to_event, only: [:create]
  #before_filter :authenticate_user!, except: [:index, :show, :new, :create]

  # GET /photos
  # GET /photos.json
  def index
    @photos = current_user.photos
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
    @state = :new
  end

  # GET /photos/1/edit
  def edit
    @state = :edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @errors = []
    @photos = []

    params[:file].each {|file|
      image = file[1]
      @photo = Photo.create(image: image)
      @photo.user = current_user
      @photo.location.save!

      if @photo.save!
        @photos << @photo
      else
        @errors << @photo.error
      end
    }
    
    Rails.logger.debug "\n\n @photos (#{@photos.count}) - #{@photos.inspect} \n\n"

    respond_to do |format|
      if @errors.empty?
        format.html { redirect_to @photo  , notice: 'Photo was successfully created.' }
        format.json { render action: 'show', status: :created, location: photo_url(@photos)}
      else
        format.html { render action: 'new' }
        format.json { render json: @errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|      
      @photo.location.description = location_params[:description]
      @photo.location.save!
      
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    def save_return_to
      # We don't have a return_to saved and the page was reloaded not redirected to
      if session[:return_to].nil? && request.referer.nil?
        session[:return_to] = photos_path
      elsif !request.referer.nil? # We do not have a reload, but a valid back url.
        session[:return_to] = request.referer
        # else we use the previously saved return_to url.
      end
      
    end
    
    def save_to_event
      Rails.logger.debug "\n\n In SAVE_TO_EVENT:: @photos #{@photos} \n\n"

      begin
        sorted_photos = @photos.sort_by!{|photo| photo.date_taken }
      rescue NoMethodError => e
        Rails.logger.debug "\n\n Error #{e.message} \n\n"
      end
      # Using the photo, determine if we already have an event based on the photo's date, location and possibly entered event. (start with date_taken first)
      
      # If we have an event for this date (/location and/or entered date criteria), then assign it.
      # If we don't create a blank event and get the Photographer to fill it out.
      @events = []
      @events_error = []
      
      sorted_photos.each {|photo| 
        @event = Event.where(event_date: photo.date_taken)
        Rails.logger.debug "\n\n @event in sorted_photos #{@event.inspect} \n\n"
        if @event.empty? 
          @event = Event.new(description: "New Event", event_date: photo.date_taken)
          if @event.save
            photo.event = @event
            photo.save
            #TODO: Add error handling here.
            @events << @event
          else
            @events_error << "Event not saved #{@event}"
          end
          Rails.logger.debug "\n\n NEW @event in sorted_photos #{@event.inspect} \n\n"
        else
          @events << @event
          #TODO: Add error handling here.
          photo.event = @event.first
          Rails.logger.info "\n\n There was more than one Event found matching this criteria #{@event.inspect} \n\n"
          photo.save
        end
      }

      Rails.logger.debug "\n\n @events #{@events.inspect} \n\n"
      Rails.logger.debug "\n\n @events_error #{@events_error.inspect} \n\n"
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:person, :location, :tags, :note, :image => [])
    end
    
    def location_params
       params.require(:location).permit(:description)
    end
    
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.haml
= form_for @photo, :html => { multipart: true, class: "dropzone", id: "my-awesome-dropzone" } do |f|

  - if @photo.errors.any?
    #error_explanation
      %h2= "#{pluralize(@photo.errors.count, "error")} prohibited this photo from being saved:"
      %ul
        - @photo.errors.full_messages.each do |msg|
          %li= msg

  .field
    = image_tag @photo.image.url(:thumb) if @photo.image.present?
  
  - if @state == :edit
    - if !current_user.guest? 
      .field
        .label Photographer
        = #{current_user.id}
    .field
      .label Where was this taken?
      = text_field :location, :description
    .field
      = f.label :tags
      = f.text_field :tags
    .field
      = f.label :note
      = f.text_field :note
    .actions
      = f.submit 'Save'

:javascript
  var state = "#{@state}";
  $("#my-awesome-dropzone").data("state", state);

app/views/photos/edit.html.haml
%h1 Editing photo

= render 'form'

= link_to 'Show', @photo
\|
= link_to 'Back', session[:return_to]

app/views/photos/index.html.haml
%h1 Listing photos

- if @photos.nil?
  %div You don't have any photos to show
  
- if @photos

  %button.prevPhotoSetBtn{id: "prevPhotoSetBtn", url: photos_path} <<
  .jcarousel
    %ul
      - @photos.each do |photo|
        %li= link_to image_tag(photo.image.url(:thumb)), "#", class: "photo", data: {photo_id:"#{photo.id}"} unless photo.image.nil?
  %button.nextPhotoSetBtn{id: "nextPhotoSetBtn", url: photos_path} >> 
    
  %table
    %tr
      %th Image
      %th Photographer
      %th Location
      %th Tags
      %th Note
      %th{colspan:3} Actions
      %th
      %th

    - @photos.each do |photo|
      %tr
        %td= image_tag photo.image.url(:thumb) unless photo.image.nil?
        %td= photo.user.guest? ? "Guest Account" : photo.user.email 
        %td= photo.location.description
        %td= photo.tags
        %td= photo.note
        %td= link_to 'Show', photo
        %td= link_to 'Edit', edit_photo_path(photo)
        %td= link_to 'Destroy', photo, :method => :delete, :data => { :confirm => 'Are you sure?' }

  %br

%div= link_to 'New Photo', new_photo_path


#showBig

app/views/photos/new.html.haml
%h1 New photo

= render 'form', photo: @photo
= link_to 'All of my photos', photos_path

app/views/photos/show.html.haml
%p#notice= notice

%p
  %b Photographer:
  = @photo.user.email if @photo.user
%p
  %b Location:
  = @photo.location.description
%p
  %b Tags:
  = @photo.tags
%p
  %b Note:
  = @photo.note
%p
  /= image_tag @photo.image.url unless @photo.image.nil?
  = image_tag @photo.image.url(:large) unless @photo.image.nil?
  = image_tag @photo.image.url(:medium) unless @photo.image.nil?
  = image_tag @photo.image.url(:thumb) unless @photo.image.nil?
= link_to 'Edit', edit_photo_path(@photo)
\|
= link_to 'All of my photos', photos_path